<a href="https://colab.research.google.com/github/Kassaum/Absenteeism-Case-Study/blob/master/Absenteeism_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Creating a Logistic regression to predict Absenteeism**

## Import the Libraries

In [0]:
import pandas as pd
import numpy as np

## Mount Drive

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## Load the Data

In [0]:
data_preprocessed = pd.read_csv('/content/drive/My Drive/Absenteeism/Absenteeism_preprocessed.csv')


In [4]:
data_preprocessed.head()


Unnamed: 0  Reason_1  Reason_2  ...  Children  Pets  Absenteeism Time in Hours
0           0         0         0  ...         2     1                          4
1           1         0         0  ...         1     0                          0
2           2         0         0  ...         0     0                          2
3           3         1         0  ...         2     0                          4
4           4         0         0  ...         2     1                          2

[5 rows x 16 columns]

In [0]:
data_preprocessed = data_preprocessed.drop(['Unnamed: 0'], axis = 1)


In [6]:
data_preprocessed.head()


Reason_1  Reason_2  Reason_3  ...  Children  Pets  Absenteeism Time in Hours
0         0         0         0  ...         2     1                          4
1         0         0         0  ...         1     0                          0
2         0         0         0  ...         0     0                          2
3         1         0         0  ...         2     0                          4
4         0         0         0  ...         2     1                          2

[5 rows x 15 columns]

## Create the target

We will take the median value of Absenteeism Time in Hours as a cut-off line

In [7]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

Moderately absent <= Median hours

Excessively absent > Median hours

In [0]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [9]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [0]:
data_preprocessed['Excessive Absenteeism'] = targets

In [11]:
data_preprocessed.head()

Reason_1  Reason_2  ...  Absenteeism Time in Hours  Excessive Absenteeism
0         0         0  ...                          4                      1
1         0         0  ...                          0                      0
2         0         0  ...                          2                      0
3         1         0  ...                          4                      1
4         0         0  ...                          2                      0

[5 rows x 16 columns]

In [12]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [0]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'], axis=1)

In [14]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  ...  Children  Pets  Excessive Absenteeism
0         0         0         0  ...         2     1                      1
1         0         0         0  ...         1     0                      0
2         0         0         0  ...         0     0                      0
3         1         0         0  ...         2     0                      1
4         0         0         0  ...         2     1                      0

[5 rows x 15 columns]

In [15]:
data_with_targets.shape

(700, 15)

In [16]:
data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  ...  Education  Children  Pets
0           0         0         0  ...          0         2     1
1           0         0         0  ...          0         1     0
2           0         0         0  ...          0         0     0
3           1         0         0  ...          0         2     0
4           0         0         0  ...          0         2     1
..        ...       ...       ...  ...        ...       ...   ...
695         1         0         0  ...          1         2     0
696         1         0         0  ...          0         1     2
697         1         0         0  ...          1         0     0
698         0         0         0  ...          1         0     0
699         0         0         0  ...          0         1     1

[700 rows x 14 columns]

In [0]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

## Standardize the Data

In [0]:
from sklearn.preprocessing import StandardScaler
absenteeism_scaler = StandardScaler()

In [19]:
absenteeism_scaler.fit(unscaled_inputs)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [0]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [21]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [22]:
scaled_inputs.shape

(700, 14)

## Split the data into train & test / Shuffle

In [0]:
from sklearn.model_selection import train_test_split

### Split

In [24]:
train_test_split(scaled_inputs, targets)

[array([[ 1.73205081, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136,  3.17979734, ..., -0.44798003,
         -0.91902997, -0.58968976],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
          2.67996851, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976]]),
 array([[-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
         -0.91902997, -0.58968976],
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
          0.88046927, -0.58968976],
        ...,
        [ 1.73205081, -0.09298136, -0.31448545, ..., -

In [0]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 20)

In [26]:
print (x_train.shape,y_train.shape)

(560, 14) (560,)


In [27]:
print (x_test.shape,y_test.shape)

(140, 14) (140,)


## Logistic Regression with Sklearn

In [0]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

### Training the Model

In [0]:
reg = LogisticRegression()

In [30]:
reg.fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [31]:
reg.score(x_train, y_train)

0.7839285714285714

## Manually check Accuracy

In [32]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [33]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [34]:
np.sum((model_outputs==y_train))

439

In [35]:
model_outputs.shape[0]

560

In [36]:
np.sum((model_outputs == y_train)) / model_outputs.shape[0]

0.7839285714285714

## Intercept and Coefficients

In [37]:
reg.intercept_


array([-0.21957576])

In [38]:
reg.coef_

array([[ 2.07452213,  0.33466331,  1.56097327,  1.32750188,  0.1878226 ,
        -0.07060017,  0.70649077, -0.03995965, -0.2009517 , -0.00462411,
         0.31937669, -0.13558227,  0.38168134, -0.33338757]])

In [39]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [0]:
feature_name = unscaled_inputs.columns.values

In [0]:
summary_table = pd.DataFrame (columns=['Feature name'], data = feature_name)

In [0]:
summary_table['Coefficient'] = np.transpose(reg.coef_)

In [43]:
summary_table

Feature name  Coefficient
0                  Reason_1     2.074522
1                  Reason_2     0.334663
2                  Reason_3     1.560973
3                  Reason_4     1.327502
4               Month Value     0.187823
5           Day of the week    -0.070600
6    Transportation Expense     0.706491
7          Distance to Work    -0.039960
8                       Age    -0.200952
9   Daily Work Load Average    -0.004624
10          Body Mass Index     0.319377
11                Education    -0.135582
12                 Children     0.381681
13                     Pets    -0.333388

In [0]:
summary_table.index = summary_table.index + 1

In [0]:
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]

In [46]:
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                 Intercept    -0.219576
1                  Reason_1     2.074522
2                  Reason_2     0.334663
3                  Reason_3     1.560973
4                  Reason_4     1.327502
5               Month Value     0.187823
6           Day of the week    -0.070600
7    Transportation Expense     0.706491
8          Distance to Work    -0.039960
9                       Age    -0.200952
10  Daily Work Load Average    -0.004624
11          Body Mass Index     0.319377
12                Education    -0.135582
13                 Children     0.381681
14                     Pets    -0.333388

## Interpreting the Coefficients

In [0]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [48]:
summary_table

Feature name  Coefficient  Odds_ratio
0                 Intercept    -0.219576    0.802859
1                  Reason_1     2.074522    7.960741
2                  Reason_2     0.334663    1.397470
3                  Reason_3     1.560973    4.763455
4                  Reason_4     1.327502    3.771610
5               Month Value     0.187823    1.206619
6           Day of the week    -0.070600    0.931834
7    Transportation Expense     0.706491    2.026866
8          Distance to Work    -0.039960    0.960828
9                       Age    -0.200952    0.817952
10  Daily Work Load Average    -0.004624    0.995387
11          Body Mass Index     0.319377    1.376270
12                Education    -0.135582    0.873207
13                 Children     0.381681    1.464745
14                     Pets    -0.333388    0.716492

In [49]:
summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficient  Odds_ratio
1                  Reason_1     2.074522    7.960741
3                  Reason_3     1.560973    4.763455
4                  Reason_4     1.327502    3.771610
7    Transportation Expense     0.706491    2.026866
13                 Children     0.381681    1.464745
2                  Reason_2     0.334663    1.397470
11          Body Mass Index     0.319377    1.376270
5               Month Value     0.187823    1.206619
10  Daily Work Load Average    -0.004624    0.995387
8          Distance to Work    -0.039960    0.960828
6           Day of the week    -0.070600    0.931834
12                Education    -0.135582    0.873207
9                       Age    -0.200952    0.817952
0                 Intercept    -0.219576    0.802859
14                     Pets    -0.333388    0.716492

## Testing the Model

In [50]:
reg.score(x_test,y_test)

0.7357142857142858

In [51]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.73825966, 0.26174034],
       [0.58795033, 0.41204967],
       [0.36712696, 0.63287304],
       [0.81162265, 0.18837735],
       [0.06127301, 0.93872699],
       [0.30690384, 0.69309616],
       [0.29493568, 0.70506432],
       [0.08079407, 0.91920593],
       [0.80400642, 0.19599358],
       [0.75999392, 0.24000608],
       [0.4622669 , 0.5377331 ],
       [0.15450706, 0.84549294],
       [0.04604734, 0.95395266],
       [0.72947484, 0.27052516],
       [0.23080142, 0.76919858],
       [0.55067175, 0.44932825],
       [0.52874769, 0.47125231],
       [0.55477826, 0.44522174],
       [0.38143834, 0.61856166],
       [0.0251927 , 0.9748073 ],
       [0.69578142, 0.30421858],
       [0.80421732, 0.19578268],
       [0.3768243 , 0.6231757 ],
       [0.39948746, 0.60051254],
       [0.18176149, 0.81823851],
       [0.75976147, 0.24023853],
       [0.46988997, 0.53011003],
       [0.88978022, 0.11021978],
       [0.13538822, 0.86461178],
       [0.79659382, 0.20340618],
       [0.

In [52]:
predicted_proba.shape

(140, 2)

In [53]:
predicted_proba[:,1]

array([0.26174034, 0.41204967, 0.63287304, 0.18837735, 0.93872699,
       0.69309616, 0.70506432, 0.91920593, 0.19599358, 0.24000608,
       0.5377331 , 0.84549294, 0.95395266, 0.27052516, 0.76919858,
       0.44932825, 0.47125231, 0.44522174, 0.61856166, 0.9748073 ,
       0.30421858, 0.19578268, 0.6231757 , 0.60051254, 0.81823851,
       0.24023853, 0.53011003, 0.11021978, 0.86461178, 0.20340618,
       0.38508703, 0.70505605, 0.70183345, 0.56406796, 0.19578268,
       0.54314403, 0.20541739, 0.82126457, 0.44520741, 0.61158096,
       0.2094607 , 0.40337164, 0.21409118, 0.09894294, 0.842517  ,
       0.66696405, 0.71725297, 0.27020317, 0.20195465, 0.1710223 ,
       0.57388094, 0.08343439, 0.67981314, 0.28675297, 0.87278627,
       0.48596026, 0.93274693, 0.24666308, 0.08214027, 0.08284243,
       0.7284407 , 0.67005252, 0.3124804 , 0.86066991, 0.18419083,
       0.26006746, 0.01324125, 0.22067156, 0.81294039, 0.31498837,
       0.20469486, 0.07167719, 0.93340874, 0.4637118 , 0.65566